Allow the raw Geometry to be passed to methods
spinen/laravel-geometry pull request #16
Opened 2017-07-30 21:00 UTC by jimmypuckett

This allows the geometries to interact with each other.  Will fix #15 .

2017-07-30 21:02 UTC, jimmypuckett commented
@ssfinney This is just a WIP, so don't accept it yet.  I am not 100% sold on the solution & I have not written any test yet.  I just pushed this up to start a discussion on the solution.

2017-08-01 01:10 UTC, jimmypuckett commented
@ssfinney If this passes, then we are good to review.  I should have coverage back up to 100%.

2017-08-01 12:21 UTC, ssfinney requested changes

2017-08-01 12:21 UTC, ssfinney commented on src/Support/GeometryProxy.php
> +        return (method_exists($argument, 'getRawGeometry')) ? $argument->getRawGeometry() : $argument;
Why make this one line into a ternary? This is less readable to me than splitting it up.

2017-08-01 12:35 UTC, jimmypuckett commented on src/Support/GeometryProxy.php
> +        return (method_exists($argument, 'getRawGeometry')) ? $argument->getRawGeometry() : $argument;
Well, I have an answer, but it is not a great one...

The code coverage sees it as one line & there is not a good way to write the test to get the else with the way that the method_exist works.  This gives me 100% without having to tweak my test ;-)

I don't mind putting it back the other way, but I am not going to mess with he required changes to the test.

Just let me know what you prefer...

2017-08-01 12:38 UTC, ssfinney commented on src/Support/GeometryProxy.php
> +        return (method_exists($argument, 'getRawGeometry')) ? $argument->getRawGeometry() : $argument;
I would rather have cleaner code than an extra 1% coverage, so keep the old.

I understand why you would push for 100 though, it's addictive!

2017-08-01 12:45 UTC, ssfinney approved these changes

2017-08-01 12:56 UTC, merged